### ISSUE TITLE
Non-printable characters.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-chronicles#10]
Sometimes you need to debug some strings which has `\r`, `\n`, `\t` characters inside, is it possible to convert such characters to `\r`, `\n`, `\t` and so on.
Also it would be nice to have some kind of hex output for some seq[byte] logs.

**Comment by zah** [comment]
It's currently possible to achieve this by writing your own formatting helpers:

``` nim
info "example", dump = data.toHex, multiLine = text.repr
```

It's possible to define a framework where such helpers will affect only some of the output types, but I don't see a good use case for this yet.

**Comment by cheatfate** [comment]
@zahary, ok lets not introduce hex conversion, but at least C symbols conversion?
The main use-case is to not break formatted output when dumping strings with CRLF.

**Comment by zah** [comment]
Can you clarify what you mean by C symbols? 
For the new lines, I've suggested using `repr`, but actually the right solution is `strutils.escape`:

``` nim
import chronicles, strutils

var str = """
some multiline
string
more lines
"""

info "long lines", s = str.escape
```

Produces:

```
[2018-06-13 12:02:53] [INFO] long lines
  thread: 0
  s: "some multiline\x0Astring\x0Amore lines\x0A"

```

Is that what you mean?

**Comment by cheatfate** [comment]
Yeah its what i mean, but `\x0A` can be replaced with `\n`, and `\x0D` can be replaced with `\r`.
https://en.wikipedia.org/wiki/Escape_sequences_in_C.
You don't need to replace unicode and other escape secuences, just most useful `\a`, `\b`, `\f`, `\n`, `\r`, `\t`, `\v`.

**Comment by zah** [comment]
Fixed, although not with the nice `\r`, `\n` symbols. I used `strutils.escape`, because I didn't want to write a new escape function. We should probably bring an issue upstream asking for a better `escape` function.
