### ISSUE TITLE
ModuleId

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-chronicles#13]
Currently `nim-chronicles` looks like this:
```
[2018-07-13 14:36:46] [INFO] Creating server on  (thread=0, address=127.0.0.1:8545, topic=HTTP-JSONRPC-SERVER)
[2018-07-13 14:36:46] [INFO] Creating server on  (thread=0, address=[::1]:8545, topic=HTTP-JSONRPC-SERVER)
[2018-07-13 14:36:46] [DEBUG] HTTP RPC server started (thread=0, address=127.0.0.1:8545, topic=HTTP-JSONRPC-SERVER)
[2018-07-13 14:36:46] [DEBUG] HTTP RPC server started (thread=0, address=[::1]:8545, topic=HTTP-JSONRPC-SERVER)
[2018-07-13 14:36:46] [INFO] Received connection (thread=0, address=127.0.0.1:61069, topic=HTTP-JSONRPC-SERVER)
```

Every log line is really missing `module name` of log producer, because if there will be like 4 different modules (`p2p-client`, `p2p-server`, `jsonrpc-client`, `jsonrpc-server`) which will produce log line `Connection Established`, you will never know which module made this log line.

For example `journalctl -xe` on Linux produces such log output:
```
Jul 13 09:44:33 phantom sudo[51692]: cheatfate : TTY=pts/3 ; PWD=/home/cheatfate/Nim ; USER=root ; COMMAND=/usr/bin/pacman -Syyu
Jul 13 09:44:33 phantom sudo[51692]: pam_unix(sudo:session): session opened for user root by cheatfate(uid=0)
Jul 13 09:45:36 phantom dbus-daemon[268]: [system] Reloaded configuration
```
As you can see here, not only `host` but also `process name` are part of log line (`sudo`, `dbus-daemon`).

**Comment by zah** [comment]
The documentation of Chronicles explicitly explains that the intended purpose of the `logScope` construct is to attach such "origin of event" properties.

It's an open question whether the default formatters should treat some of the attached properties as well-known/built-in and provide special treatment for them (the downside of doing this would be that certain general purpose filtering tools that allow you to treat all properties in the same way will be harder to create).

As for including `process name` in the logs as shown in the example, my understanding is that this extra info is automatically inserted by `journald` and this is indeed a very sensible way to approach the problem. The default configuration of Chronicles assumes the use of a sophisticated hypervisor such as `journald` as prescribed by the 12-factor app methodology:
https://12factor.net/logs

If the user wants a different behavior, the documentation mentions convenient ways to add program-wide properties (search for the `serverId` example in the README).
