### ISSUE TITLE
escape is [deprecated]

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-chronicles#14]
Currently usage of nim-chronicles generates a bunch of warning messages like this:
```
chronicles-0.2.0\chronicles.nim(211, 36) template/generic instantiation from here
chronicles-0.2.0\chronicles\log_output.nim(315, 15) Warning: escape is deprecated [Deprecated]
```

**Comment by Yardanico** [comment]
also nim compiler and nimble generate these warnings :)

**Comment by cheatfate** [comment]
@Yardanico, so this is reason why we don't need to fix chronicles?
