### ISSUE TITLE
Log filters.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-chronicles#17]
While producing big amount of log entries it would be very nice to have some kind of filters.
For example `geth` has `--vmodule` option where you can specify filters.
```
--vmodule value           Per-module verbosity: comma-separated list of <pattern>=<level> (e.g. eth/*=5,p2p=4)
```
With such setting you can apply many filters at once, not just only one or complex one with `grep`. Also in such way you can change level of verbosity for specific modules.

**Comment by zah** [comment]
In the original vision for the library, there is a `chonicles-tails` tool that is able to filter the logs in various interactive ways (it can inside a terminal or provide a web GUI). I still think this is the best approach, because you can develop a richer UI in such a dedicated filtering tool.

**Comment by yglukhov** [comment]
Embedding `libcronicles-tails` into `chronicles` for runtime filtering should serve both purposes. While `chronicles-tails` is a nice and useful concept I think it's a slightly harder to setup, when all you want is just iterate-compile-run-see-output-startover. E.g. one of my common workflows is:
1. Clear terminal and `clear; tmux clear-history; nim c -r myprogram.nim`, that's two keystrokes.
3. Observe output.
4. Write code
5. Repeat

`chronicles-tails` would add complexity to such workflow, not to mention learning about it, while adding a couple of filtering flags to step 1 would be a breeze.

**Comment by zah** [comment]
Well, we already have compile-time filtering support and run-time filtering support in Chronicles. We could add the per-topic log level setting to get feature parity with what was described in Geth.

But my point about UI was that sometimes you want to change the filtering settings without restarting the process and that's where a specialized GUI can come in handy (otherwise, each project will have to invent it on their own).

**Comment by zah** [comment]
Here is a minimal spec for enhancing the current per-topic filtering:

1) Modify the compile-time option `chronicles_enabled_topics` to also allow specifying the log level. The syntax could be `-d:chronicles_enabled_topics:MyTopic:DEBUG,AnotherTopic:5`

2) Modify the run-time `setTopicState` to also specify the topic log level (one of the options should be "default", which means "follow the current global configuration").

I'll describe the possible task of implementing `chronicles-tail` in a separate issue.

**Comment by kdeme** [comment]
As mentioned before, I'll start working on this.

**Comment by StatusSceptre** [comment]
Do we still want a bounty on this?

**Comment by arnetheduck** [comment]
already implemented it seems
