### ISSUE TITLE
Source code files names and line numbers.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-chronicles#18]
Is it possible to add this information to produced logs too?

**Comment by zah** [comment]
It's possible to add this. Perhaps a good task for a bounty.

**Comment by zah** [comment]
Here is the spec for the bounty:

1. Add new compile-time option `chronicles_line_numbers` (off by default). It will set the default mode for the entire project.

2. Recognize `chroniclesLineNumbers = true/false` as a special property that can be set in a lexical scope or for a particular log statment (we may decide to rename this to something shorter later).

The file/line-number information can be easily obtained with `instantiationInfo`.

**Comment by kdeme** [comment]
I can work on this task

**Comment by zah** [comment]
@kdeme, great, do you need any help finding your way through the code? You can usually find me on Gitter in the `status-im/nimbus` channel.

**Comment by kdeme** [comment]
OK, perfect. So far I think I can get started, but I'll join the channel as I'm sure I'll have questions eventually.

**Comment by kdeme** [comment]
Well done @surf1nb1rd 

I too have an implementation ready, however I was trying to get in contact on gitter with @zah to discuss the format of the filename/line in the logs first. 

E.g Should it be printed as just an additional property (as in the PR of surf1nb1rd), or should it be printed in a more explicit way, like is done with topics, timestamp, etc.
My idea would be the latter, as it has nothing really to do with the actual values in the code.

**Comment by kdeme** [comment]
@zah, no problem, not your fault. You are right about getting to know the inner workings of the library. I can have a look at another issue.

**Comment by zah** [comment]
Imlemented in c990e83
