### ISSUE TITLE
Implement a proper test suite

### ISSUE THREAD

**Issue by zah** [status-im/nim-chronicles#20]
Chronicles supports a great number of compile-time options that make it hard to test with standard unit tests. Instead, the test suite should consist of example programs and test case files that specify how these programs should be compiled and what is the expected output.

Several such programs are already present in https://github.com/status-im/nim-chronicles/tree/master/tests

The next step is the creation of a test runner that:

1) Search for *.test files present under the `tests` folder and its sub-folders.

2) Compiles and executes a program specified in the `.test` file using some provided settings. Compares the output of the program with an output block also specified in the `.test` file.

3) Cleans up any created intermediate files.

The format of the `.test` file might be the following:

``` bash
program = long_lines
sinks = textblocks,textlines[nocolors,file(foo.log)]
colors = AnsiColors

--- STDOUT ---
[2018-08-22 19:27:43] [[32mINFO[0m] [[93mmain[0m] [1mmain started
[0m  [34mthread: [1m0
[0m  [34ma: [1m10
[0m  [34marg: [1m50
[0m  [34mb: [1minner-b
[0m  [34mc: [1m10
[0m  [34md: [1msome-d
[0m  [34mx: [1m16
[0m  [34mz: [1m20
[0m
[2018-08-22 19:27:43] [[32mINFO[0m] [1mexiting
[0m  [34mthread: [1m0
[0m  [34ma: [1m12
[0m  [34mb: [1moverriden-b
[0m  [34mc: [1m100
[0m  [34mmsg: [1mbye bye
[0m  [34mx: [1m16
[0m
--- FILE foo.log ---
[2018-08-22 19:27:18] [INFO] [main] main started (thread=0, a=10, arg=50, b=inner-b, c=10, d=some-d, x=16, z=20)
[2018-08-22 19:27:18] [INFO] exiting (thread=0, a=12, b=overriden-b, c=100, msg=bye bye, x=16)
```

That is, the file begins with a number of Chronicles `-d:` settings and other well-known test options, followed by expected outcome such as particular stdout or file contents, or an expected compile-time error.

The test suite should cover all existing Chronicles settings in various combinations. On Unix systems, it may use `chroot` to ensure that no other files besides the specified are created by the tested program.

**Comment by zah** [comment]
@arnetheduck has voiced support for this in [another issue](https://github.com/status-im/nim-chronicles/issues/29), so this bounty may be considered approved.

It was [requested as a next task](https://github.com/status-im/nim-chronicles/pull/31#issuecomment-418657819) by @kdeme. Given the less enjoyable nature of this issue, I think we can set the reward to 500 USD if all of the suggested features are implemented.

**Comment by arnetheduck** [comment]
is there a framework ready that can be used for this? it sounds like a maintenance burden to develop one just for the purpose. ie testament in compiler does something similar

**Comment by zah** [comment]
`testament` is not developed as a reusable framework, but it would be nice if the work created here is somewhat suitable for upstreaming into the standard libraries of Nim. It's probably better if our own team takes care of creating such a pull request after the bounty here has been delivered.

**Comment by kdeme** [comment]
I had a quick look around for existing framework earlier, but did not find anything. 
I did not discover testament at that point, but then again it is not very documented ;).

However, I had a look at it now and I think it could be interesting. 
But, instead of what is purposed here, you have to set the test "spec" in a discard statement in the actual test code.
It does look like in its current form it is very much crafted to run from the nim directory (with koch or tester directly), but with some changes it could be used I guess. I think you will still have to add the code yourself to e.g. check output to a file and possibly other more special output tests (timestamps?).

Anyway, as a very quick test I wrote some code to read out a config file (the test file) with parsecfg and compile/run the test and compare output. Nothing special, but I could continue to build on this.
In the end, maintenance of the testrunner is one thing, creating and maintaining the actual tests is probably a bigger work.

Of course I would prefer working on something that has higher chance of reuse, and testament as it is now looks decent already.

Let me know your thoughts...

**Comment by zah** [comment]
The format in `testament` doesn't match our requirements. The examples there are compiled only in few different modes that must produce the same output. What we need here is different outputs depending on the compilation setting.

The potential for reuse lies in the lower-level primitives that will be developed - things like invoking the compiler expecting a certain error message, executing a program expecting a certain output, "scoped" helpers for executing series of commands with automatic file-system clean up at the end, etc.

**Comment by kdeme** [comment]
Perhaps rather dirty, but there is a way to achieve this with testament, for example by creating different test files that look something like this:
```
discard """
  cmd: "nim $target -d:chronicles_sinks=textlines[stdout] -d:chronicles_colors=AnsiColors $options $file"
  output: '''[32mINF[0m [1mmain started                              [0m topics="[93mmain[0m" [32mthread[0m=[94m0[0m [32ma[0m=[94m10[0m [32marg[0m=[94m50[0m [32mb[0m=[94minner-b[0m [32mc[0m=[94m10[0m [32md[0m=[94msome-d[0m [32mx[0m=[94m16[0m [32mz[0m=[94m20[0m
[32mINF[0m [1mexiting                                   [0m [32mthread[0m=[94m0[0m [32ma[0m=[94m12[0m [32mb[0m=[94moverriden-b[0m [32mc[0m=[94m100[0m [32mmsg[0m=[94m"bye bye"[0m [32mx[0m=[94m16[0m
'''
"""

include lexical_scopes
```
Or adapt the test code to have a public proc and import it.
This does kinda defeat the benefit that testament has with having the spec on the same location as the test code.

And it still needs the additional code for parsing correctly the different output options, output to files, deleting files, etc. And most work will probably go into this anyhow.

**Comment by zah** [comment]
Yes, let's aim for the original spec here and keep in mind that some of the lower-level primitives can be kept in a module that may be extracted in a separate package later or submitted for inclusion in the Nim's standard library (as additional predicates for the `unittest` module).

**Comment by zah** [comment]
This bounty has been delivered by @kdeme in the linked pull request.
A reward of 500 USD has been paid out here:
https://etherscan.io/tx/0xd8cceb26021705d007fef692540dbd7ea516a2a0ab65a46537efc2dec6cee22d
