### ISSUE TITLE
key-values reordered in text log output

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-chronicles#22]
The following log statement:

    debug(
    "GAS CONSUMPTION", total = gasMeter.gasRemaining + amount, amount, remaining = gasMeter.gasRemaining, reason)

Will print:

    [2018-08-22 18:45:54] [DEBUG] GAS CONSUMPTION (thread=0, amount=3, reason=Push1, remaining=4294967293, topic=gas, total=4294967296)

Notice how the fields have changed order

**Comment by zah** [comment]
The fields are sorted before being printed (although only the statically known ones). The reasoning here was that this would help the user find a particular field more quickly.

Perhaps your expectation is that the users would arrange the fields by importance by themselves and I could agree with that, but it's a bit less clear how to handle injected fields from log scopes then (e.g. they might come last for example).

**Comment by arnetheduck** [comment]
Yeah, I think that's a reasonable expectation - when calling log it visually looks very similar to the output with syntax and all, so I'd also expect order to stay the same.

Not sure about logscopes, but an advantage of putting that stuff before params is that multiple logs in a row from the same scope will have similar "prefix" alignment. A predictable placement of them I think will help in general, given that they're used to display "common" information (and thus it makes sense that they're always in the same place - last or first - regardless of what other fields are being logged)

Another thing to think about here is the possibility that both log line and scope contain values with the same key.. what happens then?
