### ISSUE TITLE
Time format misdocumented

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-chronicles#23]
Documentation states that timestamps in text format are formatted according to RFC3339 - however, the format is actually a custom format with the following deviations:

* ` ` instead of `T` used as separator
* timezone is missing

Either documentation or format needs changing

**Comment by arnetheduck** [comment]
if we fix the separator (use `T`), we can claim it's an ISO8601 datetime without timezone (RFC3339 is a special case of that)..

**Comment by zah** [comment]
I lost the reference, but I initially used ISO8601 in the docs, then found out that RFC3339 allows the omission of the `T` separator (and removing it was much more visually pleasing to my eyes).

**Comment by zah** [comment]
From RFC3339:

```
      NOTE: ISO 8601 defines date and time separated by "T".
      Applications using this syntax may choose, for the sake of
      readability, to specify a full-date and full-time separated by
      (say) a space character.
```

https://tools.ietf.org/html/rfc3339

**Comment by arnetheduck** [comment]
mm right, missed that - it's not part of the BNF spec - it still doesn't allow the omission of timezone however so you can't have both.

the lack of timezone is worse for json where the expectation is that a tool will pick it up and make sense of the data - can't do that if it's incomplete
