### ISSUE TITLE
does Nim 0.19.0 really exists?

### ISSUE THREAD

**Issue by ba0f3** [status-im/nim-chronicles#3]
https://github.com/status-im/nim-chronicles/blob/945d422153c12010addc4dfdf9f102ac2fbd7787/chronicles.nimble#L10

**Comment by zah** [comment]
Sorry, sometimes I forget that not everyone has access to the secret lab where the next versions of Nim are cooked up ;)

**Comment by ba0f3** [comment]
thank you, lol. cant wait to see new nim version
