### ISSUE TITLE
Unable to add chronicles as a dependency

### ISSUE THREAD

**Issue by syhpoon** [status-im/nim-chronicles#51]
Hi there,

Sorry if this is something trivial, but I'm unable to add `chronicles` as dep to my library.
When I add `requires "chronicles"` to my <project>.nimble and run `nimble build`, I get this error:

```
 Verifying dependencies for wut@0.1.0
 Installing chronicles@any version
Downloading https://github.com/status-im/nim-chronicles using git
  Verifying dependencies for chronicles@0.5.1
       Tip: 15 messages have been suppressed, use --verbose to show them.
     Error: Unsatisfied dependency: nim (>= 0.18.1)
```

My nim version is:
```
nim -v
Nim Compiler Version 0.19.4 [Linux: amd64]
Compiled at 2019-02-01
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: b6d96cafc8bcad1f3d32f2910b25cd11a93f7751
active boot switches: -d:release
```

on Arch Linux. What is it I'm doing wrong here?

**Comment by stefantalpalaru** [comment]
Can you please run Nimble with `--debug` and post the full output?

**Comment by syhpoon** [comment]
Okay, so while reading through the `--debug` output I found what was the problem myself.
It turned out I had installed nim using `pacman` some time ago (pre 0.18.0) and then recently I did the same using `choosenim`, which installed the most recent one. And these two somehow conflicted with each other.
Once I removed the old version, the project builds successfully now.

Sorry for the false alarm :)
