### ISSUE TITLE
Need understandable document to get start

### ISSUE THREAD

**Issue by geohuz** [status-im/nim-chronicles#63]
I can't see a clear way on how to generate a structured log(json) file, i'm following the document by using

``nim -r -d:release -d:chronicles_sinks="textlines[nocolors],json[file(mylog.json, truncate)]" c heartbeat.nim``

and getting the following error:

``
.nimble/pkgs/chronicles-0.6.0/chronicles/log_output.nim(753, 24) template/generic instantiation of `createStreamRecordTypes` from here
.nimble/pkgs/chronicles-0.6.0/chronicles/log_output.nim(234, 23) Error: index out of bounds, the container is empty
``

I guess reading the document and the test code are really frustrating for new comer comparing to reading the python logging module. It should be made clear and straight forward, for example there is a screen shot on json logging generated, but I can't find the script showed in pic.

**Comment by alehander42** [comment]
Sorry!

**Comment by alehander42** [comment]
This can be fixed in two ways:

* the readme says "The default value is `DEBUG` in debug builds and `INFO` in
release mode.", so you can skip `-d:release` or pass the `-d:chronicles_log_level` to be DEBUG
* you should use textlines[stdout,nocolors] (or at least this works for me)

**Comment by alehander42** [comment]
otherwise you are correct, that maybe small reproducable examples should be added in the README

**Comment by alehander42** [comment]
bigger examples based on real world projects are still useful, so they should just remain side by side

**Comment by geohuz** [comment]
Thanks @alehander42 , that solves my problem!
