### ISSUE TITLE
Make sure `trace` statements are side-effect free

### ISSUE THREAD

**Issue by zah** [status-im/nim-chronicles#73]
Similar to `debugEcho`, `trace` statements should not be considered side-effects in a program. This makes it easier to use the `func` keyword and Chronicles-based printf-debugging at the same time.

**Comment by zedeus** [comment]
The issue here is `strformat` which can raise `ref ValueError`. Replacing with `strutils.%` doesn't help as it also raises `ValueError`. I tried using a template/macro to wrap it in a try-except but ran into various errors.
