### ISSUE TITLE
Runtime configuration.

### ISSUE THREAD

**Issue by cheatfate** [status-im/nim-chronicles#9]
It would be nice to have ability to change options not only at compile time, but at runtime too.
For example i have configuration file which has path, where my project needs to store log. How i can achieve this?
Also it would be nice to change all options at runtime.

**Comment by zah** [comment]
This is on my to-do list. I'll push an example for setting a run-time file path today.

**Comment by zah** [comment]
Implemented, you can find the docs here:
https://github.com/status-im/nim-chronicles#working-with-file-outputs
