### ISSUE TITLE
spurious Exception raised on windows

### ISSUE THREAD

**Issue by arnetheduck** [status-im/nim-chronicles#92]
No idea what to make of this:
* https://github.com/status-im/nim-libp2p/runs/2065518281?check_suite_focus=true fails 
* https://github.com/status-im/nim-libp2p/actions/runs/635454957 works - 
 
The only difference is https://github.com/status-im/nim-libp2p/commit/9970e6eeb5f6ca1bd4613b61a1ccca73f037be61 but there are other `raises: [Defect]` functions that do logging in that module, and that don't fail.

**Comment by jangko** [comment]
The exception appear too when nimbus-eth1 compiled with '-d:chronicles_log_level=TRACE' or  '-d:chronicles_log_level=DEBUG' on Windows. But will silent if no `chronicles_log_level` used.

**Comment by jangko** [comment]
Turn out this is a `std/terminal` issue. One of chronicles backend write text to stdout/stderr using `std/terminal`.
Almost all call to `std/terminal` that contains `getTerminal` will raise this `Exception`.
Both Nim 1.2.6 and Nim 1.2.10 will fail to compile this snippet, but ok with Nim 1.5.1

```Nim
import std/terminal

proc test() {.raises: [Defect].} = 
  let term = isTrueColorSupported()
  
test()
```
